CREATE TABLE IF NOT EXISTS cba_presets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    content TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE arma3server ADD COLUMN cba_preset_id INTEGER REFERENCES cba_presets(id) ON DELETE SET NULL;
